### ISSUE TITLE
Display 2020 Accordion Item only if has Tributes

### ISSUE THREAD

**Issue by shazahm1** [School-Apps-Today/Issue-Tracker#3]
Timesheet

- [x] Edit cMap template to only show the Tributes accordion item if one exist. .9

**Comment by shazahm1** [comment]
Timesheet

- [ ] Item One

**Comment by shazahm1** [comment]
Not sure this is easily possible. The reason being the posts will be displayed by DPS. there is not a way to know if DPS are going to show results or not.

**Comment by jaf3778** [comment]
**Not sure this is easily possible**
I was thinking that it would only show if the user actually has a post on
the site. If they have no posts then it would not show. Is that possible?

**Comment by shazahm1** [comment]
I believe I already said I do not think this is possible because there is not a way for the template to know if it should show an accordion item based on whether or not DPS has results to display  or not.

**Comment by jaf3778** [comment]
**I believe I already said I do not think this is possible because there is
not a way for the template to know if it should show an accordion item
based on whether or not DPS has results to display or not.**

Okay, it was just wishful thinking I guess. Because I am used to
connections which only displays those accordions if they have something in
them. I know this is different but it just got my wheels turning :-)

**Comment by shazahm1** [comment]
The only way for this to work would to be to build a plugin which reads the DPS shortcode, but instead of displaying posts, returns a count, that way it can be determined if the accordion item should display or not.

(mouse died, so I lost a few hours :/ )

**Comment by jaf3778** [comment]
**The only way for this to work would to be to build a plugin which reads
the DPS shortcode, but instead of displaying posts, returns a count, that
way it can be determined if the accordion-item should display or not.**
This would be a very cool feature but not a priority.

**Comment by jaf3778** [comment]
**The only way for this to work would to be to build a plugin which reads
the DPS shortcode, but instead of displaying posts, returns a count, that
way it can be determined if the accordion item should display or not.  **

When you say build a plugin, do you mean that it is not possible with a
snippet or something? In other words, I am just trying to draw a mental
line between snippets and plugins. I am just used to you saying custom
coded or snippet and things like that, so I am just asking while it came
up. Please don't think I am questioning the complexity of what it would
take to complete it, just trying to understand a little better where the
need for a plugin kicks in, Thank you!

**Comment by shazahm1** [comment]
it could be a snippet. you question would get different answers from different people...

for me, a snippet is a relatively short single purpose piece of code. most often you'll find people saying add this code or that code to the theme's functions.php file. we just happen to use code snippets for its ease of use and portability of the code snippets.

when things get complex and require lots of coding, that's when I want to do plugins. this way I can set the "project" in my IDE which nets me code completion and code assist ... basically features that make it easier and faster for me to code with less bugs/typos. I'm not a wizard, I try to invest in good tools.

**Comment by jaf3778** [comment]
How long do you think it would take you to build this as a fairly solid
piece of coded machinery?

**Comment by shazahm1** [comment]
> would take you to build this as a fairly solid
> piece of coded machinery?

I do not know about "_solid piece of coded machinery_" but, if I duplicate DPS, rip out anything that renders posts and have it return a count instead. Let's say an hour. As with anything, unforeseen obstacles may take longer.

**Comment by jaf3778** [comment]
I do not know about "*solid piece of coded machinery*" but, if I duplicate
DPS, rip out anything that renders posts and have it return a count
instead. Let's say an hour. As with anything, unforeseen obstacles may take
longer.

That sounds worth it for sure! I understand what you mean about
unforeseen obstacles. I was just inquiring further per the plugin term. If
you have time for this one today, it would be after the others, just FYI

**Comment by shazahm1** [comment]
ok, I got this done ... and under an hour :)

I did not end up doing the plugin to count posts as I immediately run into an issue which would take me sometime to figure out.

I did come up with a rather hacky hack :)

I check the bio field for the DPS shortcode, if it exists I add a filter to DPS which sets a custom no posts message. I then process the DPS shortcode and check for that message, if it is found I set a flag and remove hat filter. If that flag is set then the tribute accordion is displayed. This all happens within the cMap template so it'll not affect anything else :)

**Comment by shazahm1** [comment]
- https://marlboroschools.schoolappstoday.com/bank/
- https://marlboroschools.schoolappstoday.com/sehs-view/

**Comment by jaf3778** [comment]
The accordion is looking good!

**Comment by jaf3778** [comment]
Sounds like a pretty awesome work around :-)
